### ISSUE TITLE
Elm on Node

### ISSUE THREAD

**Issue by patrickdet** [rtfeldman/elm-node-app#1]
Hey @rtfeldman,

I just came across this repo and read some of the code. I see that you are starting with a concept of a `Supervisor` and a `Worker` and it makes me wonder whether node.js is the ideal platform for elm on the server. Instead of creating platform bindings for node wouldn't it almost make more sense for the community to think about a second compilation target for Elm, to a more robust platform like the BEAM (Erlang VM) for example?

This is most likely not the right place to discuss that and getting things running on node is probably easier than adding another compile target. Other than that, really looking forward to seeing what Elm for Node looks like 👍 

Cheers,

Patrick

**Comment by rtfeldman** [comment]
I agree on all counts! This is not intended to run a webserver, it's intended to run CLI code where you want to make use of multiple cores.

(Like, say, hypothetically, a test runner. 😉 )
